export const typingCurriculum = {
  lessons: [
    {
      id: "eng-beginner-home-row-01",
      title: "Home Row Foundation",
      chapter: "Beginner / Chapter 1",
      difficulty: "beginner",
      duration: 165,
      language: "english",
      lessonType: "home-row",
      targetWPM: 20,
      accuracyGoal: 96,
      level: "Beginner",
      text: "For accuracy and speed to work together, keep an even posture and maintain a disciplined finger position. The left hand shall rest lightly on A, S, D, and F, and the right hand shall rest on J, K, L, and the semicolon key. Each keystroke should be deliberate rather than forceful, with the wrists kept steady and the forearms relaxed. Type one key, then return immediately to the home-row anchor before moving to the next letter. When a mistake occurs, refrain from rapid re-typing; instead, complete the immediate word, then correct with controlled precision. The aim of this practice is to develop a consistent touch, stable rhythm, and reliable spacing so that the typed output remains readable even under timed conditions. Over time, this method builds muscle memory for common government-office phrases, enabling you to reproduce names, dates, and file references without hesitation. Maintain calm breathing and a steady gaze on the current line; do not let your eyes lag behind the fingers. By following this protocol daily, you will establish the foundation required for official correspondence, exam-style dictation, and professional data entry.",
    },
    {
      id: "eng-beginner-basic-words-01",
      title: "Basic Words and Easy Sentences",
      chapter: "Beginner / Chapter 2",
      difficulty: "beginner",
      duration: 175,
      language: "english",
      lessonType: "basic-words",
      targetWPM: 22,
      accuracyGoal: 95,
      level: "Beginner",
      text: "In an administrative section, a clerk prepares the file cover, aligns the pages, and records the receipt time in the register. A candidate for recruitment reads the notice carefully, notes the schedule, and verifies the required documents before submitting the application. When the office opens, the dealing assistant sorts the incoming correspondence, marks each item for the appropriate section, and forwards it with a brief remark. Type every short word with measured keystrokes, keeping spaces exact and punctuation clear. If a letter is missed, pause briefly, restore the correct spelling, and continue without breaking the flow of the sentence. The objective of this exercise is to train steady reading, controlled hand movement, and consistent formatting so that official entries remain accurate even when the pace gradually increases. Over repeated practice, your typing speed improves because errors decrease and your mind spends less time correcting avoidable mistakes. This approach is particularly useful for government notices, instructions, and application forms where clarity and order are essential. Maintain calm posture, breathe evenly, and treat each line as a small record that must be fit for official use.",
    },
    {
      id: "eng-beginner-key-drill-01",
      title: "Common Keyboard Drill",
      chapter: "Beginner / Chapter 3",
      difficulty: "beginner",
      duration: 165,
      language: "english",
      lessonType: "keyboard-drill",
      targetWPM: 24,
      accuracyGoal: 94,
      level: "Beginner",
      text: "receipt file dispatch docket memorandum schedule clerk verifier approval register endorsement acknowledgement signature annexure committee panel order circular note compliance reference procedure classification official designation department division desk section file number subject heading record keeping quality inspection",
    },
    {
      id: "eng-intermediate-accuracy-01",
      title: "Accuracy Exercise: Official Details",
      chapter: "Intermediate / Chapter 1",
      difficulty: "intermediate",
      duration: 240,
      language: "english",
      lessonType: "accuracy",
      targetWPM: 30,
      accuracyGoal: 95,
      level: "Intermediate",
      text: "For recruitment procedures to remain transparent, every selection notice must contain the administrative essentials: the schedule date, the reporting time, the document list to be carried, and the verification desk or counter details. Candidates are required to read each line as written, because omissions in file preparation often lead to avoidable deferrals. The application form should be filled with correct personal particulars, and the declarations must match the supporting documents. Before submission, verify that the photograph, signature, category information, and mandatory declarations are placed in the prescribed manner. The aim is not merely to fill the form quickly, but to produce an entry that can be checked without ambiguity. When accuracy is maintained at the first attempt, the verification staff can complete scrutiny within the expected timeline and the department can proceed with further steps without interruptions. Practice this lesson by typing the instructions steadily, respecting commas, full stops, and spacing exactly as shown. If you notice a discrepancy between what you type and what appears on the screen, complete the current sentence, then correct the words with controlled accuracy rather than hurried backtracking. This method trains responsible data handling, which is a core skill for clerical posts where official records must remain consistent, auditable, and reliable.",
    },
    {
      id: "eng-intermediate-speed-01",
      title: "Speed Drill: Office Workflow",
      chapter: "Intermediate / Chapter 2",
      difficulty: "intermediate",
      duration: 420,
      language: "english",
      lessonType: "speed",
      targetWPM: 40,
      accuracyGoal: 92,
      level: "Intermediate",
      text: "In a routine office cycle, incoming correspondence is received first at the dealing counter and then registered in a movement register. The file is sorted category-wise so that each item reaches the correct division without delay. After sorting, the clerk stamps the receipt and ensures that the date of receipt is recorded consistently across the cover and the inward sheet. The file is then scanned, and the scanned copy is matched with the physical pages to avoid missing enclosures. The assistant prepares a short office note describing the reference received, the action required, and the present stage of the file. Enclosures are verified against the enclosure list; if anything is missing, the deficiency is recorded with a clear remark and the file is not pushed forward blindly. Once the verification is complete, the assistant forwards the file with a suggested course of action for consideration by the dealing officer. Type the process description with uniform spacing and precise punctuation, because speed should never compromise the official meaning of the record. When typing at a higher pace, keep your eyes on the next instruction while completing the current phrase, and avoid stopping between clauses. If you need to correct an error, return to the correct word and continue forward so the final output remains a coherent administrative statement. This lesson is designed to develop disciplined speed in file movement, supporting accuracy of registers, and improving the reliability of office workflows.",
    },
    {
      id: "eng-intermediate-mixed-01",
      title: "Mixed Characters and Symbols",
      chapter: "Intermediate / Chapter 3",
      difficulty: "intermediate",
      duration: 150,
      language: "english",
      lessonType: "mixed-characters",
      targetWPM: 32,
      accuracyGoal: 94,
      level: "Intermediate",
      text: "Receipt No. 245/SSC/2026 was recorded in the inward register at 10:45 AM on the basis of the candidate’s submission. The scrutiny staff confirmed the prescribed fee of Rs. 100 and noted that the form status was marked as Pending for verification of supporting documents. The processing desk assigned the file to the appropriate section and stamped the reference on the acknowledgment sheet to maintain traceability. If the applicant provided any scanned attachments, the receiving clerk cross-checked that the filenames were legible and that the pages were in the correct order before moving the file forward. The helpdesk contact was displayed for reference as support@sasacademy.in, and the candidate was informed that future updates will be communicated according to the workflow schedule. During typing practice, reproduce each administrative element precisely: the receipt number, the timestamp, the fee figure, the status term, and the contact email. Do not alter abbreviations; keep capitalization and punctuation exact, especially around the slash separators and the time format. Maintain consistent spacing after full stops, because official records rely on uniform formatting to support audits and internal queries. When typing at speed, focus on completing the full sentence before making corrections, so that the final output forms a stable official statement suitable for record-keeping. This exercise is designed to strengthen accuracy with numbers, slashes, and punctuation in SSC-style documentation.",
    },
    {
      id: "eng-advanced-ssc-chsl-dest-01",
      title: "SSC CHSL DEST Style Passage",
      chapter: "Advanced / Exam Simulation",
      difficulty: "advanced",
      duration: 600,
      language: "english",
      lessonType: "ssc-chsl-dest",
      targetWPM: 35,
      accuracyGoal: 95,
      level: "SSC CHSL DEST",
      text: "The Staff Selection Commission conducts skill tests to assess the practical typing ability of candidates for clerical and data entry posts. During the test, candidates must maintain speed, accuracy, and composure. They should read the passage carefully, avoid unnecessary corrections, and type each word exactly as printed. In government offices, accurate data entry supports public service delivery, record maintenance, and timely communication between departments.",
    },
    {
      id: "eng-advanced-ssc-steno-01",
      title: "SSC Steno Typing Style Content",
      chapter: "Advanced / Steno Practice",
      difficulty: "advanced",
      duration: 600,
      language: "english",
      lessonType: "ssc-steno",
      targetWPM: 45,
      accuracyGoal: 94,
      level: "SSC Steno",
      text: "Honourable members are informed that the committee reviewed the progress of digital record management and recommended timely training for all staff. The report emphasized disciplined documentation, transparent procedures, and quick retrieval of public information. The department will issue revised instructions after receiving comments from regional offices.",
    },
    {
      id: "eng-advanced-high-speed-01",
      title: "High-Speed Professional Drill",
      chapter: "Advanced / Speed Control",
      difficulty: "advanced",
      duration: 600,
      language: "english",
      lessonType: "high-speed",
      targetWPM: 50,
      accuracyGoal: 92,
      level: "Advanced",
      text: "Consistent typing speed is built through relaxed shoulders, precise finger travel, and confident spacing. Do not strike the keys with force. Let the hands move lightly, keep the eyes ahead of the current word, and maintain a smooth pace until the final line.",
    },
    {
      id: "eng-exam-formal-01",
      title: "Formal Government Paragraph",
      chapter: "Exam Practice / Formal English",
      difficulty: "exam",
      duration: 600,
      language: "english",
      lessonType: "exam-practice",
      targetWPM: 38,
      accuracyGoal: 95,
      level: "Exam Practice",
      text: "All candidates are advised to preserve their admit card until the completion of the recruitment process. The admit card contains important details such as roll number, examination centre, reporting time, and instructions regarding permitted items. Any request for change of centre shall not be entertained after the scheduled deadline.",
    },
    {
      id: "eng-coding-practice-01",
      title: "Coding Typing Practice",
      chapter: "Special Practice / Coding",
      difficulty: "intermediate",
      duration: 150,
      language: "english",
      lessonType: "coding",
      targetWPM: 30,
      accuracyGoal: 96,
      level: "Coding",
      text: "const score = Math.max(0, accuracy - errors); function formatResult(wpm, accuracy) { return String(wpm) + ' WPM with ' + String(accuracy) + '% accuracy'; }",
    },
    {
      id: "eng-motivation-daily-01",
      title: "Daily Motivation Challenge",
      chapter: "Daily Practice",
      difficulty: "daily",
      duration: 90,
      language: "english",
      lessonType: "daily-challenge",
      targetWPM: 32,
      accuracyGoal: 94,
      level: "Daily Challenge",
      text: "A disciplined learner does not wait for confidence before practice. Confidence grows after repeated effort. Type with patience today, review every mistake, and return tomorrow with a sharper rhythm.",
    },
    {
      id: "hin-beginner-home-row-01",
      title: "हिंदी प्रारंभिक अभ्यास",
      chapter: "Beginner Hindi / Chapter 1",
      difficulty: "beginner",
      duration: 600,
      language: "hindi",
      lessonType: "hindi-basic",
      targetWPM: 12,
      accuracyGoal: 94,
      level: "Hindi Beginner",
      text: "हिंदी टाइपिंग में शुद्धता सबसे पहले आती है। प्रत्येक अक्षर, मात्रा और रिक्त स्थान को ध्यान से टाइप करें। धीरे अभ्यास करें और हर पंक्ति के बाद अपनी गलती पहचानें।",
    },
    {
      id: "hin-intermediate-office-01",
      title: "हिंदी कार्यालय अभ्यास",
      chapter: "Intermediate Hindi / Office Work",
      difficulty: "intermediate",
      duration: 180,
      language: "hindi",
      lessonType: "hindi-accuracy",
      targetWPM: 22,
      accuracyGoal: 94,
      level: "Hindi Intermediate",
      text: "कार्यालय में पत्र, सूचना, आदेश और रिपोर्ट को सही रूप में टाइप करना आवश्यक होता है। गलत मात्रा या गलत विराम चिन्ह से वाक्य का अर्थ बदल सकता है।",
    },
    {
      id: "hin-ssc-exam-01",
      title: "हिंदी SSC शैली अनुच्छेद",
      chapter: "Hindi Exam Practice",
      difficulty: "exam",
      duration: 600,
      language: "hindi",
      lessonType: "hindi-ssc",
      targetWPM: 30,
      accuracyGoal: 95,
      level: "Hindi SSC",
      text: "कर्मचारी चयन परीक्षा में अभ्यर्थी को निर्धारित समय में दिए गए अनुच्छेद को सही और स्पष्ट रूप से टाइप करना होता है। गति के साथ शुद्धता बनाए रखना आवश्यक है। नियमित अभ्यास से उंगलियों की गति, ध्यान और आत्मविश्वास में सुधार होता है।",
    },
    {
      id: "hin-daily-challenge-01",
      title: "हिंदी दैनिक चुनौती",
      chapter: "Daily Hindi Practice",
      difficulty: "daily",
      duration: 90,
      language: "hindi",
      lessonType: "daily-challenge",
      targetWPM: 20,
      accuracyGoal: 94,
      level: "Hindi Daily",
      text: "आज का अभ्यास शांत मन से करें। पहले शुद्धता पर ध्यान दें, फिर गति बढ़ाएं। सही अभ्यास की छोटी आदत लंबे समय में बड़ा परिणाम देती है।",
    },
  ],
  aiExercises: [
    {
      id: "ai-left-index-correction",
      title: "Weak-Key Correction: F G R T V B",
      difficulty: "intermediate",
      duration: 90,
      language: "english",
      lessonType: "weak-key-correction",
      targetWPM: 26,
      accuracyGoal: 96,
      text: "firm grain river table value branch frame target govern travel brief gather",
    },
    {
      id: "ai-right-hand-symbols",
      title: "Symbol Control Drill",
      difficulty: "advanced",
      duration: 90,
      language: "english",
      lessonType: "symbol-correction",
      targetWPM: 28,
      accuracyGoal: 97,
      text: "Report No. 18/2026; fee: Rs. 100; time: 09:30 AM; status: Approved; file: CHSL-DEST-04.",
    },
    {
      id: "ai-repeat-mistake-spacing",
      title: "Repeated Mistake Drill: Spacing",
      difficulty: "beginner",
      duration: 60,
      language: "english",
      lessonType: "mistake-correction",
      targetWPM: 20,
      accuracyGoal: 98,
      text: "one file one form one date one record one notice one order one office one section one signature",
    },
    {
      id: "ai-hindi-matra-drill",
      title: "हिंदी मात्रा सुधार अभ्यास",
      difficulty: "intermediate",
      duration: 600,
      language: "hindi",
      lessonType: "hindi-mistake-correction",
      targetWPM: 18,
      accuracyGoal: 96,
      text: "सूचना परीक्षा परिणाम कार्यालय प्रक्रिया प्रशिक्षण अभ्यर्थी नियमित अभ्यास शुद्धता गति",
    },
  ],
  challenges: [
    {
      id: "daily-english-accuracy",
      title: "Daily Accuracy Set",
      difficulty: "daily",
      duration: 90,
      language: "english",
      lessonType: "daily-practice",
      targetWPM: 30,
      accuracyGoal: 96,
      text: "Review the line, type with control, and correct your habit after the attempt. A clean paragraph is better than a fast paragraph full of errors.",
    },
    {
      id: "weekly-ssc-simulation",
      title: "Weekly SSC Simulation",
      difficulty: "weekly",
      duration: 600,
      language: "english",
      
      lessonType: "weekly-practice",
      targetWPM: 35,
      accuracyGoal: 95,
      text: "The weekly simulation is designed to build exam stamina. Candidates should complete the passage without depending on backspace, maintain a consistent pace, and check their result summary after submission. Regular timed practice improves both speed and confidence.",
    },
  ],
};

export const passages = {
  english: [
    ...typingCurriculum.lessons.filter((item) => item.language === "english"),
    ...typingCurriculum.aiExercises.filter((item) => item.language === "english"),
    ...typingCurriculum.challenges.filter((item) => item.language === "english"),
  ],
  hindi: [
    ...typingCurriculum.lessons.filter((item) => item.language === "hindi"),
    ...typingCurriculum.aiExercises.filter((item) => item.language === "hindi"),
    ...typingCurriculum.challenges.filter((item) => item.language === "hindi"),
  ],
};

export const modeConfig = {
  practice: {
    label: "Typing Practice",
    duration: 600,
    backspaceDisabled: false,
  },
  ssc: {
    label: "SSC Simulation",
    duration: 600,
    backspaceDisabled: true,
  },
  accuracy: {
    label: "Accuracy Training",
    duration: 180,
    backspaceDisabled: true,
  },
  speed: {
    label: "Speed Training",
    duration: 60,
    backspaceDisabled: false,
  },
  challenge: {
    label: "Daily Challenge",
    duration: 90,
    backspaceDisabled: true,
  },
};

export const fingerLessons = [
  {
    zone: "Left little",
    keys: "Q A Z",
    chapter: "Finger Placement / Left Hand",
    difficulty: "beginner",
    note: "Use the little finger for outer-left keys and return to A after every stroke.",
    drill: "qa az za aq qaz aza",
  },
  {
    zone: "Left ring",
    keys: "W S X",
    chapter: "Finger Placement / Left Hand",
    difficulty: "beginner",
    note: "Keep the ring finger relaxed; press W, S, and X without moving the whole hand.",
    drill: "ws sx xw swx wsx",
  },
  {
    zone: "Left middle",
    keys: "E D C",
    chapter: "Finger Placement / Left Hand",
    difficulty: "beginner",
    note: "Use D as the home anchor and move vertically for E and C.",
    drill: "ed dc ce deed coded",
  },
  {
    zone: "Index fingers",
    keys: "R T F G V B Y U H J N M",
    chapter: "Finger Placement / Center Keys",
    difficulty: "intermediate",
    note: "Index fingers carry the center columns; avoid stretching other fingers unnecessarily.",
    drill: "firm gate river judge number travel",
  },
  {
    zone: "Right middle",
    keys: "I K ,",
    chapter: "Finger Placement / Right Hand",
    difficulty: "intermediate",
    note: "Return to K after I and comma; this improves punctuation control.",
    drill: "ki ik, kilo kind, ink",
  },
  {
    zone: "Right ring/little",
    keys: "O P L ; . /",
    chapter: "Finger Placement / Symbols",
    difficulty: "advanced",
    note: "Control symbols with short movement and keep the palm steady.",
    drill: "op lo; plan. proof / policy",
  },
];

export const keyboardRows = [
  ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
  ["A", "S", "D", "F", "G", "H", "J", "K", "L"],
  ["Z", "X", "C", "V", "B", "N", "M", ",", ".", "/"],
];
